# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Modem
version:      1.47
version_from: Modem.pm
installdirs:  site
requires:
    Device::SerialPort:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
